title: Healthcare Researcher
logo: /profilepic.jpeg
description: |
  🧬 M.S. Health Data Science Candidate @ UCSF
  🎓 B.S. Bioinformatics @ UC Santa Cruz
show_downloads: false
theme: jekyll-theme-minimal
 
